package app

// demoPreviews is what a link preview would have found on each demo site:
// its page title and a line about it. Written here because the demo fetches
// no page; the Bookmarks view and the preview cards read them as they read a
// fetched preview.
var demoPreviews = map[string][2]string{
	"https://github.com/":                        {"GitHub", "Where the world builds software: code hosting, pull requests, issues and Actions."},
	"https://gitlab.com/":                        {"GitLab", "One application for source code, CI/CD, issues and the rest of the DevSecOps cycle."},
	"https://codeberg.org/":                      {"Codeberg", "A non-profit, community-led home for free and open-source projects, running Forgejo."},
	"https://stackoverflow.com/":                 {"Stack Overflow", "Questions and answers for programmers, with an answer for nearly every error message."},
	"https://developer.mozilla.org/":             {"MDN Web Docs", "Documentation for HTML, CSS, JavaScript and the web platform's APIs."},
	"https://go.dev/doc/":                        {"Documentation - The Go Programming Language", "Tutorials, the language spec, Effective Go and the standard library."},
	"https://doc.rust-lang.org/book/":            {"The Rust Programming Language", "The official book: ownership, borrowing, traits and fearless concurrency."},
	"https://docs.python.org/3/":                 {"Python 3 documentation", "The tutorial, the library reference and the language reference."},
	"https://nodejs.org/docs/latest/api/":        {"Node.js Documentation", "The API reference for the latest Node.js release, module by module."},
	"https://devdocs.io/":                        {"DevDocs API Documentation", "Many API references in one fast, searchable interface that also works offline."},
	"https://regex101.com/":                      {"regex101: build, test, and debug regex", "Test regular expressions with an explanation of every token and live matches."},
	"https://caniuse.com/":                       {"Can I use... Support tables for HTML5, CSS3, etc", "Which browsers support which web features, version by version."},
	"https://crontab.guru/":                      {"Crontab.guru - The cron schedule expression editor", "Type a cron expression and read in plain words when it will run."},
	"https://excalidraw.com/":                    {"Excalidraw", "A virtual whiteboard for sketching hand-drawn-looking diagrams."},
	"https://jwt.io/":                            {"JSON Web Tokens - jwt.io", "Decode, verify and generate JSON Web Tokens in the browser."},
	"https://news.ycombinator.com/":              {"Hacker News", "Links and discussion about programming, startups and whatever gratifies curiosity."},
	"https://lobste.rs/":                         {"Lobsters", "A computing-focused link aggregation community with tags and invitations."},
	"https://dev.to/":                            {"DEV Community", "Articles and discussion by and for software developers."},
	"https://changelog.com/":                     {"Changelog", "News and podcasts for developers about software and open source."},
	"https://pve.proxmox.com/wiki/Main_Page":     {"Proxmox VE wiki", "Documentation for Proxmox Virtual Environment: VMs, containers, storage and clusters."},
	"https://www.truenas.com/docs/":              {"TrueNAS Documentation Hub", "Guides and references for TrueNAS SCALE and CORE."},
	"https://docs.unraid.net/":                   {"Unraid Docs", "Documentation for the Unraid OS: the array, shares, Docker and VMs."},
	"https://docs.docker.com/":                   {"Docker Docs", "Guides and references for Docker Engine, Compose and Build."},
	"https://hub.docker.com/":                    {"Docker Hub Container Image Library", "Find and share container images for apps, databases and base systems."},
	"https://docs.opnsense.org/":                 {"OPNsense documentation", "Manuals for the open-source firewall and routing platform."},
	"https://tailscale.com/":                     {"Tailscale", "A WireGuard-based mesh VPN that connects your devices wherever they are."},
	"https://www.wireguard.com/":                 {"WireGuard: fast, modern, secure VPN tunnel", "A simple VPN that lives in the kernel and uses modern cryptography."},
	"https://docs.pi-hole.net/":                  {"Pi-hole documentation", "Network-wide ad blocking through your own DNS server."},
	"https://www.home-assistant.io/":             {"Home Assistant", "Open-source home automation that puts local control and privacy first."},
	"https://esphome.io/":                        {"ESPHome", "Control ESP32 and ESP8266 boards with simple configuration files."},
	"https://www.zigbee2mqtt.io/":                {"Zigbee2MQTT", "Use Zigbee devices without the vendor's bridge or gateway."},
	"https://www.servethehome.com/":              {"ServeTheHome", "Server, storage and networking reviews for the homelab and beyond."},
	"https://www.reddit.com/r/homelab/":          {"r/homelab", "Show off your rack, ask about hardware, and learn from other homelabbers."},
	"https://awesome-selfhosted.net/":            {"awesome-selfhosted", "A list of free software network services and web applications you can host yourself."},
	"https://selfh.st/":                          {"selfh.st", "Self-hosting news, a weekly newsletter and a directory of apps."},
	"https://www.reddit.com/r/selfhosted/":       {"r/selfhosted", "A place to share, discuss and find alternatives to hosted services."},
	"https://www.linuxserver.io/":                {"LinuxServer.io", "Container images for popular self-hosted apps, kept up to date."},
	"https://nextdash.cc/":                       {"nextDash", "A self-hosted, keyboard-first dashboard for your bookmarks and services."},
	"https://jellyfin.org/":                      {"Jellyfin", "The free software media system: your movies, shows and music, streamed by you."},
	"https://immich.app/":                        {"Immich", "Self-hosted photo and video backup with a familiar timeline and mobile apps."},
	"https://nextcloud.com/":                     {"Nextcloud", "Files, calendar, contacts and office on a server you control."},
	"https://github.com/dani-garcia/vaultwarden": {"Vaultwarden", "A lightweight Bitwarden-compatible password manager server written in Rust."},
	"https://docs.paperless-ngx.com/":            {"Paperless-ngx", "Scan, index and archive your paper documents with full-text search."},
	"https://github.com/louislam/uptime-kuma":    {"Uptime Kuma", "A self-hosted monitoring tool with status pages and notifications."},
	"https://doc.traefik.io/traefik/":            {"Traefik Proxy Documentation", "A reverse proxy that configures itself from Docker labels and other providers."},
	"https://caddyserver.com/docs/":              {"Caddy Documentation", "The web server with automatic HTTPS and a one-line config for most sites."},
	"https://letsencrypt.org/docs/":              {"Let's Encrypt Documentation", "Free, automated TLS certificates, and how ACME clients get them."},
}
