#!/bin/sh
# Prints the release tag the Docker build should stamp as VERSION: the first
# entry of static/data/whats-new/index.json, which is already the one place a
# release keeps the version current (see release_version.go's
# readLatestReleaseTag, which reads the same field at runtime for the same
# reason). The first entry counts even when it carries "hideFromModal": true —
# a hidden release still shipped and still owns the version number.
#
# Used by the Makefile's `up`/`build`/`build-clean` targets, which export the
# result as VERSION before invoking `docker compose`; docker-compose.yml and
# docker-compose.prod.yml interpolate it into the image build's --build-arg.
# A plain `docker build` that never runs this script still works — the
# Dockerfile's own `ARG VERSION=dev` default is untouched.
#
# index.json is generated by scripts/extract-whats-new-json.mjs and
# scripts/split-whats-new-releases.mjs with JSON.stringify(..., null, 2), so
# it is always one field per line; this relies on that formatting rather than
# a full JSON parser.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
index_json="$script_dir/../static/data/whats-new/index.json"

grep -m1 '"tag"' "$index_json" | sed -E 's/.*"tag": *"([^"]+)".*/\1/'
